/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAssinaturaRouteImport } from './routes/_authenticated/assinatura'
import { Route as AuthenticatedCaixaRouteImport } from './routes/_authenticated/caixa'
import { Route as AuthenticatedPreparoRouteImport } from './routes/_authenticated/preparo'
import { Route as AuthenticatedRelatoriosRouteImport } from './routes/_authenticated/relatorios'
import { Route as AuthenticatedSaidasRouteImport } from './routes/_authenticated/saidas'
import { Route as AuthenticatedVendasRouteImport } from './routes/_authenticated/vendas'
import { Route as BancadaTokenRouteImport } from './routes/bancada.$token'
import { Route as ApiPublicKirvanoRouteImport } from './routes/api/public/kirvano'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAssinaturaRoute = AuthenticatedAssinaturaRouteImport.update({
  id: '/assinatura',
  path: '/assinatura',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCaixaRoute = AuthenticatedCaixaRouteImport.update({
  id: '/caixa',
  path: '/caixa',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPreparoRoute = AuthenticatedPreparoRouteImport.update({
  id: '/preparo',
  path: '/preparo',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRelatoriosRoute = AuthenticatedRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSaidasRoute = AuthenticatedSaidasRouteImport.update({
  id: '/saidas',
  path: '/saidas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVendasRoute = AuthenticatedVendasRouteImport.update({
  id: '/vendas',
  path: '/vendas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const BancadaTokenRoute = BancadaTokenRouteImport.update({
  id: '/bancada/$token',
  path: '/bancada/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicKirvanoRoute = ApiPublicKirvanoRouteImport.update({
  id: '/api/public/kirvano',
  path: '/api/public/kirvano',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/assinatura': typeof AuthenticatedAssinaturaRoute
  '/caixa': typeof AuthenticatedCaixaRoute
  '/preparo': typeof AuthenticatedPreparoRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/saidas': typeof AuthenticatedSaidasRoute
  '/vendas': typeof AuthenticatedVendasRoute
  '/bancada/$token': typeof BancadaTokenRoute
  '/api/public/kirvano': typeof ApiPublicKirvanoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/assinatura': typeof AuthenticatedAssinaturaRoute
  '/caixa': typeof AuthenticatedCaixaRoute
  '/preparo': typeof AuthenticatedPreparoRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/saidas': typeof AuthenticatedSaidasRoute
  '/vendas': typeof AuthenticatedVendasRoute
  '/bancada/$token': typeof BancadaTokenRoute
  '/api/public/kirvano': typeof ApiPublicKirvanoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/assinatura': typeof AuthenticatedAssinaturaRoute
  '/_authenticated/caixa': typeof AuthenticatedCaixaRoute
  '/_authenticated/preparo': typeof AuthenticatedPreparoRoute
  '/_authenticated/relatorios': typeof AuthenticatedRelatoriosRoute
  '/_authenticated/saidas': typeof AuthenticatedSaidasRoute
  '/_authenticated/vendas': typeof AuthenticatedVendasRoute
  '/bancada/$token': typeof BancadaTokenRoute
  '/api/public/kirvano': typeof ApiPublicKirvanoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/assinatura'
    | '/caixa'
    | '/preparo'
    | '/relatorios'
    | '/saidas'
    | '/vendas'
    | '/bancada/$token'
    | '/api/public/kirvano'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin'
    | '/assinatura'
    | '/caixa'
    | '/preparo'
    | '/relatorios'
    | '/saidas'
    | '/vendas'
    | '/bancada/$token'
    | '/api/public/kirvano'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/assinatura'
    | '/_authenticated/caixa'
    | '/_authenticated/preparo'
    | '/_authenticated/relatorios'
    | '/_authenticated/saidas'
    | '/_authenticated/vendas'
    | '/bancada/$token'
    | '/api/public/kirvano'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  BancadaTokenRoute: typeof BancadaTokenRoute
  ApiPublicKirvanoRoute: typeof ApiPublicKirvanoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assinatura': {
      id: '/_authenticated/assinatura'
      path: '/assinatura'
      fullPath: '/assinatura'
      preLoaderRoute: typeof AuthenticatedAssinaturaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/caixa': {
      id: '/_authenticated/caixa'
      path: '/caixa'
      fullPath: '/caixa'
      preLoaderRoute: typeof AuthenticatedCaixaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/preparo': {
      id: '/_authenticated/preparo'
      path: '/preparo'
      fullPath: '/preparo'
      preLoaderRoute: typeof AuthenticatedPreparoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/relatorios': {
      id: '/_authenticated/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof AuthenticatedRelatoriosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/saidas': {
      id: '/_authenticated/saidas'
      path: '/saidas'
      fullPath: '/saidas'
      preLoaderRoute: typeof AuthenticatedSaidasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vendas': {
      id: '/_authenticated/vendas'
      path: '/vendas'
      fullPath: '/vendas'
      preLoaderRoute: typeof AuthenticatedVendasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/bancada/$token': {
      id: '/bancada/$token'
      path: '/bancada/$token'
      fullPath: '/bancada/$token'
      preLoaderRoute: typeof BancadaTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/kirvano': {
      id: '/api/public/kirvano'
      path: '/api/public/kirvano'
      fullPath: '/api/public/kirvano'
      preLoaderRoute: typeof ApiPublicKirvanoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAssinaturaRoute: typeof AuthenticatedAssinaturaRoute
  AuthenticatedCaixaRoute: typeof AuthenticatedCaixaRoute
  AuthenticatedPreparoRoute: typeof AuthenticatedPreparoRoute
  AuthenticatedRelatoriosRoute: typeof AuthenticatedRelatoriosRoute
  AuthenticatedSaidasRoute: typeof AuthenticatedSaidasRoute
  AuthenticatedVendasRoute: typeof AuthenticatedVendasRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAssinaturaRoute: AuthenticatedAssinaturaRoute,
  AuthenticatedCaixaRoute: AuthenticatedCaixaRoute,
  AuthenticatedPreparoRoute: AuthenticatedPreparoRoute,
  AuthenticatedRelatoriosRoute: AuthenticatedRelatoriosRoute,
  AuthenticatedSaidasRoute: AuthenticatedSaidasRoute,
  AuthenticatedVendasRoute: AuthenticatedVendasRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  BancadaTokenRoute: BancadaTokenRoute,
  ApiPublicKirvanoRoute: ApiPublicKirvanoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
