// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://inrnuaqblqrwgvsvqgte.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imlucm51YXFibHFyd2d2c3ZxZ3RlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODU0MjY4OTIsImV4cCI6MjEwMTAwMjg5Mn0.pSd5ey2-fXDLtErMb0zSeZ1PHiVRfXc6vF1Vb1T0yiE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});